#!/usr/bin/env python3
"""Measure the concrete up/down GEMMs generated by Person 2 sweep cases."""

from __future__ import annotations

import argparse
import json
import statistics
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Iterable

import torch
import torch.nn.functional as F
from torch.profiler import ProfilerActivity, profile

from bench_person2_ffn import Case, SWEEP_SHAPES, make_input, percentile
from torch_transformer_benchmark import BaselineTransformerBlock


@dataclass(frozen=True)
class GemmShape:
    name: str
    m: int
    n: int
    k: int

    @property
    def flops(self) -> int:
        return 2 * self.m * self.n * self.k


@dataclass(frozen=True)
class GemmResult:
    case: str
    stage: str
    m: int
    n: int
    k: int
    median_ms: float
    p90_ms: float
    effective_tflops: float
    profiled_cuda_ms: float
    kernel_names: tuple[str, ...]


@dataclass(frozen=True)
class AlgorithmResult:
    case: str
    algorithm_index: int
    correctness_passed: bool
    max_abs: float
    failed_elements: int
    median_ms: float | None
    p90_ms: float | None


def gemm_shapes(case: Case) -> tuple[GemmShape, GemmShape]:
    tokens = case.batch * case.seq_len
    return (
        GemmShape("up", tokens, case.ffn_dim, case.d_model),
        GemmShape("down", tokens, case.d_model, case.ffn_dim),
    )


def cuda_event_samples(
    operation: Callable[[], torch.Tensor], repeats: int
) -> list[float]:
    starts = [torch.cuda.Event(enable_timing=True) for _ in range(repeats)]
    ends = [torch.cuda.Event(enable_timing=True) for _ in range(repeats)]
    torch.cuda.synchronize()
    with torch.inference_mode():
        for index in range(repeats):
            starts[index].record()
            operation()
            ends[index].record()
    torch.cuda.synchronize()
    return [start.elapsed_time(end) for start, end in zip(starts, ends)]


def profile_kernels(
    operation: Callable[[], torch.Tensor], iterations: int
) -> tuple[float, tuple[str, ...]]:
    with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as trace:
        with torch.inference_mode():
            for _ in range(iterations):
                operation()
        torch.cuda.synchronize()

    device_us = 0.0
    kernels: set[str] = set()
    for event in trace.events():
        device_type = str(getattr(event, "device_type", "")).lower()
        if "cuda" not in device_type:
            continue
        duration = float(getattr(event, "duration_time_ns", 0.0) or 0.0) / 1000.0
        if duration <= 0:
            duration = float(getattr(event, "self_device_time_total", 0.0) or 0.0)
        device_us += duration
        kernels.add(str(getattr(event, "name", getattr(event, "key", "unknown"))))
    return device_us / iterations / 1000.0, tuple(sorted(kernels))


def measure_stage(
    case: Case,
    shape: GemmShape,
    stage: str,
    operation: Callable[[], torch.Tensor],
    warmups: int,
    repeats: int,
    profile_iterations: int,
) -> GemmResult:
    with torch.inference_mode():
        for _ in range(warmups):
            operation()
    torch.cuda.synchronize()
    samples = cuda_event_samples(operation, repeats)
    profiled_ms, kernels = profile_kernels(operation, profile_iterations)
    median_ms = statistics.median(samples)
    return GemmResult(
        case=case.label,
        stage=stage,
        m=shape.m,
        n=shape.n,
        k=shape.k,
        median_ms=median_ms,
        p90_ms=percentile(samples, 0.90),
        effective_tflops=shape.flops / (median_ms * 1e9),
        profiled_cuda_ms=profiled_ms,
        kernel_names=kernels,
    )


def print_result(result: GemmResult) -> None:
    print(
        f"{result.stage}: M={result.m} N={result.n} K={result.k} | "
        f"median={result.median_ms:.4f} ms | p90={result.p90_ms:.4f} ms | "
        f"effective={result.effective_tflops:.3f} TFLOP/s | "
        f"profiled_cuda={result.profiled_cuda_ms:.4f} ms"
    )
    print("kernels=" + (", ".join(result.kernel_names) or "<none>"))


def measure_cublaslt_algorithms(
    case: Case,
    block: BaselineTransformerBlock,
    args: argparse.Namespace,
) -> list[AlgorithmResult]:
    """Validate every returned heuristic before reporting its latency."""
    from person2_ffn_fusion import load_down_extension

    extension = load_down_extension()
    device = block.ffn_out.weight.device
    calibrations = []
    algorithm_count = None
    for seed in (args.seed, args.seed + 1, args.seed + 2):
        x, mask = make_input(case, device, torch.float16, seed)
        tokens = case.batch * case.seq_len
        with torch.inference_mode():
            normalized = block.norm2(x).reshape(tokens, case.d_model)
            hidden = F.gelu(block.ffn_in(normalized), approximate="none").contiguous()
            residual = x.reshape(tokens, case.d_model).contiguous()
            reference = residual + F.linear(
                hidden, block.ffn_out.weight, block.ffn_out.bias
            )
            reference = reference.masked_fill(~mask.reshape(-1, 1), 0)
        output = torch.empty_like(residual)
        if algorithm_count is None:
            algorithm_count = extension.down_algorithm_count(
                hidden,
                residual,
                block.ffn_out.weight,
                block.ffn_out.bias,
                output,
            )
        calibrations.append((hidden, residual, mask.reshape(-1), reference, output))

    results: list[AlgorithmResult] = []
    assert algorithm_count is not None
    for algorithm_index in range(algorithm_count):
        max_abs = 0.0
        failed = 0
        for hidden, residual, mask, reference, output in calibrations:
            extension.down_residual_masked_algorithm_out(
                hidden,
                residual,
                block.ffn_out.weight,
                block.ffn_out.bias,
                mask,
                algorithm_index,
                output,
            )
            error = (output.float() - reference.float()).abs()
            passed = torch.isfinite(output) & torch.isfinite(reference)
            passed &= (error <= args.atol) | (
                error <= args.rtol * reference.float().abs()
            )
            max_abs = max(max_abs, float(error.max().item()))
            failed += int((~passed).sum().item())

        median_ms = None
        p90_ms = None
        if failed == 0:
            hidden, residual, mask, _reference, output = calibrations[0]

            def operation() -> torch.Tensor:
                extension.down_residual_masked_algorithm_out(
                    hidden,
                    residual,
                    block.ffn_out.weight,
                    block.ffn_out.bias,
                    mask,
                    algorithm_index,
                    output,
                )
                return output

            with torch.inference_mode():
                for _ in range(args.warmup):
                    operation()
            torch.cuda.synchronize()
            samples = cuda_event_samples(operation, args.repeats)
            median_ms = statistics.median(samples)
            p90_ms = percentile(samples, 0.90)

        result = AlgorithmResult(
            case=case.label,
            algorithm_index=algorithm_index,
            correctness_passed=failed == 0,
            max_abs=max_abs,
            failed_elements=failed,
            median_ms=median_ms,
            p90_ms=p90_ms,
        )
        results.append(result)
        timing = (
            f"median={median_ms:.4f} ms p90={p90_ms:.4f} ms"
            if median_ms is not None and p90_ms is not None
            else "timing=SKIPPED"
        )
        print(
            f"cuBLASLt algorithm={algorithm_index} | "
            f"accuracy={'PASS' if failed == 0 else 'FAIL'} | "
            f"max_abs={max_abs:.6g} | failed={failed} | {timing}"
        )
    return results


def cases_from_args(args: argparse.Namespace) -> Iterable[Case]:
    if args.sweep:
        return (Case(*shape) for shape in SWEEP_SHAPES)
    return (
        Case(
            args.batch_size,
            args.seq_len,
            args.d_model,
            args.heads,
            args.ffn_dim,
            args.causal,
            args.padding_ratio,
        ),
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sweep", action="store_true")
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--seq-len", type=int, default=512)
    parser.add_argument("--d-model", type=int, default=512)
    parser.add_argument("--heads", type=int, default=8)
    parser.add_argument("--ffn-dim", type=int, default=2048)
    parser.add_argument("--causal", action="store_true")
    parser.add_argument("--padding-ratio", type=float, default=0.0)
    parser.add_argument("--seed", type=int, default=1234)
    parser.add_argument("--warmup", type=int, default=20)
    parser.add_argument("--repeats", type=int, default=100)
    parser.add_argument("--profile-iterations", type=int, default=20)
    parser.add_argument("--atol", type=float, default=0.001)
    parser.add_argument("--rtol", type=float, default=0.01)
    parser.add_argument("--cublaslt-algorithms", action="store_true")
    parser.add_argument("--json-output", type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if not torch.cuda.is_available():
        raise RuntimeError("the per-GEMM profile requires CUDA")
    device = torch.device("cuda")
    dtype = torch.float16
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)
    print(
        f"torch={torch.__version__} | cuda={torch.version.cuda} | "
        f"gpu={torch.cuda.get_device_name(device)} | dtype={dtype}"
    )

    results: list[GemmResult] = []
    algorithm_results: list[AlgorithmResult] = []
    for case in cases_from_args(args):
        print(f"\n{case.label}")
        block = BaselineTransformerBlock(
            case.d_model, case.heads, case.ffn_dim
        ).to(device=device, dtype=dtype).eval()
        x, mask = make_input(case, device, dtype, args.seed)
        del mask
        tokens = case.batch * case.seq_len
        with torch.inference_mode():
            normalized = block.norm2(x).reshape(tokens, case.d_model)
            linear_up = F.linear(normalized, block.ffn_in.weight, block.ffn_in.bias)
            hidden = F.gelu(linear_up, approximate="none")
            residual = x.reshape(tokens, case.d_model)
        up_shape, down_shape = gemm_shapes(case)
        stages = (
            (
                up_shape,
                "up_linear",
                lambda: F.linear(
                    normalized, block.ffn_in.weight, block.ffn_in.bias
                ),
            ),
            (
                up_shape,
                "up_linear_exact_gelu",
                lambda: F.gelu(
                    F.linear(normalized, block.ffn_in.weight, block.ffn_in.bias),
                    approximate="none",
                ),
            ),
            (
                down_shape,
                "down_linear",
                lambda: F.linear(hidden, block.ffn_out.weight, block.ffn_out.bias),
            ),
            (
                down_shape,
                "down_linear_residual",
                lambda: residual
                + F.linear(hidden, block.ffn_out.weight, block.ffn_out.bias),
            ),
        )
        for shape, name, operation in stages:
            result = measure_stage(
                case,
                shape,
                name,
                operation,
                args.warmup,
                args.repeats,
                args.profile_iterations,
            )
            results.append(result)
            print_result(result)
        if args.cublaslt_algorithms:
            algorithm_results.extend(
                measure_cublaslt_algorithms(case, block, args)
            )
        torch.cuda.empty_cache()

    if args.json_output is not None:
        args.json_output.parent.mkdir(parents=True, exist_ok=True)
        args.json_output.write_text(
            json.dumps(
                {
                    "gemms": [asdict(result) for result in results],
                    "cublaslt_algorithms": [
                        asdict(result) for result in algorithm_results
                    ],
                },
                indent=2,
            ),
            encoding="utf-8",
        )
        print(f"wrote {args.json_output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
